@echo off
chcp 65001 >nul
echo ===============================================
echo   GitHub 仓库初始化脚本
echo ===============================================
echo.

cd /d D:\pythonshiyan\webauto

echo [1/6] 初始化 Git 仓库...
git init

echo.
echo [2/6] 添加远程仓库...
echo 请输入你的 GitHub 仓库 URL，例如：
echo   https://github.com/你的用户名/仓库名.git
echo.
set /p REPO_URL="远程仓库 URL: "

if not "%REPO_URL%"=="" (
    git remote add origin %REPO_URL%
    echo 已添加远程仓库: %REPO_URL%
)

echo.
echo [3/6] 创建 gh-pages 分支（用于 GitHub Pages）...
git checkout --orphan gh-pages
git rm -rf --cached .
git clean -fdx
echo # WebAuto Test Reports > README.md
git add README.md
git commit -m "Initial gh-pages branch for Allure reports"
git checkout main 2>nul || git checkout master

echo.
echo [4/6] 提交所有代码...
git add .
git status

echo.
set /p CONFIRM="确认提交所有文件? (y/n): "
if /i "%CONFIRM%"=="y" (
    git commit -m "feat: WebAuto 测试平台初始配置
    
    - 27 个测试用例 (YAML)
    - pytest 测试框架
    - GitHub Actions CI/CD
    - Allure 报告自动部署
    
    Generated by CodeBuddy"
    
    echo.
    echo [5/6] 推送到 GitHub...
    git push -u origin main
    git push origin gh-pages
    
    echo.
    echo [6/6] GitHub 配置说明
    echo ==============================================
    echo.
    echo 请在 GitHub 仓库设置中完成以下配置：
    echo.
    echo 1. 启用 GitHub Pages:
    echo    Settings ^> Pages ^> Source: Deploy from a branch
    echo    Branch: gh-pages, Folder: / (root)
    echo.
    echo 2. 启用 Actions 写权限:
    echo    Settings ^> Actions ^> General
    echo    Workflow permissions: Read and write permissions
    echo.
    echo 3. 设置 BASE_URL（可选）:
    echo    Settings ^> Secrets and variables ^> Actions
    echo    添加 BASE_URL: http://your-api-server.com
    echo.
    echo 报告访问地址:
    echo    https://你的用户名.github.io/仓库名/
    echo ==============================================
) else (
    echo 已取消提交
)

echo.
echo 完成！
echo.
pause
