# Generated by Django 6.0.4 on 2026-04-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('module', models.CharField(max_length=100, verbose_name='所属模块')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('test_id', models.CharField(max_length=200, verbose_name='测试ID/函数名')),
                ('case_type', models.CharField(choices=[('ui', 'UI 测试'), ('api', 'API 测试'), ('e2e', 'E2E 测试')], default='api', max_length=10, verbose_name='用例类型')),
                ('priority', models.IntegerField(choices=[(0, 'P0 - 阻塞'), (1, 'P1 - 严重'), (2, 'P2 - 一般'), (3, 'P3 - 低')], default=2, verbose_name='优先级')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('docstring', models.TextField(blank=True, default='', verbose_name='函数文档')),
                ('timeout', models.IntegerField(default=300, verbose_name='超时时间(秒)')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用'), ('deprecated', '已废弃')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最后运行时间')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'test_cases',
                'ordering': ['-priority', 'module', 'name'],
                'constraints': [models.UniqueConstraint(fields=('file_path', 'test_id'), name='unique_file_test')],
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套件名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('parallel', models.BooleanField(default=False, verbose_name='并行执行')),
                ('workers', models.IntegerField(blank=True, default=2, null=True, verbose_name='并行数')),
                ('marker', models.CharField(blank=True, default='', max_length=50, verbose_name='pytest标记过滤')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cases', models.ManyToManyField(related_name='suites', to='cases.testcase', verbose_name='包含用例')),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'db_table': 'test_suites',
            },
        ),
    ]
