# Generated by Django 6.0.4 on 2026-04-26 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('task_type', models.CharField(choices=[('single', '单个用例'), ('batch', '批量用例'), ('suite', '套件执行'), ('all', '全部执行')], default='batch', max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消'), ('timeout', '超时')], default='pending', max_length=20, verbose_name='状态')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='执行配置')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='结果摘要')),
                ('allure_report_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Allure报告路径')),
                ('trace_files', models.JSONField(blank=True, default=list, verbose_name='Trace文件列表')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='进程PID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='定时任务')),
                ('cron_expression', models.CharField(blank=True, default='', max_length=100, verbose_name='Cron表达式')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(default='system', max_length=50, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '测试任务',
                'verbose_name_plural': '测试任务',
                'db_table': 'test_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('DEBUG', 'DEBUG'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], default='INFO', max_length=10, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.testtask')),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
                'db_table': 'task_logs',
                'ordering': ['timestamp'],
            },
        ),
    ]
