# Generated by Django 6.0.4 on 2026-04-26 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllureReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='报告名称')),
                ('report_dir', models.CharField(max_length=500, verbose_name='报告目录路径')),
                ('total', models.IntegerField(default=0, verbose_name='总用例数')),
                ('passed', models.IntegerField(default=0, verbose_name='通过')),
                ('failed', models.IntegerField(default=0, verbose_name='失败')),
                ('broken', models.IntegerField(default=0, verbose_name='损坏')),
                ('skipped', models.IntegerField(default=0, verbose_name='跳过')),
                ('pass_rate', models.FloatField(default=0.0, verbose_name='通过率')),
                ('duration', models.FloatField(default=0.0, verbose_name='执行时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allure_report_record', to='tasks.testtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': 'Allure报告',
                'verbose_name_plural': 'Allure报告',
                'db_table': 'allure_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=200, verbose_name='文件名')),
                ('filepath', models.CharField(max_length=500, verbose_name='文件完整路径')),
                ('filesize', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('test_case', models.CharField(blank=True, default='', max_length=200, verbose_name='关联用例名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='tasks.testtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': 'Trace文件',
                'verbose_name_plural': 'Trace文件',
                'db_table': 'trace_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
